name: moodmeal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  android_alarm_manager_plus: ^4.0.7
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  http: ^1.4.0
  path_provider: ^2.0.15
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/menu.png" 

flutter:
  uses-material-design: true
